# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: CV Maria Tsagiopoulou
title: Postdoctoral researcher
email: maria.tsagiopoulou@cnag.crg.eu
#website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: tsayo7
github_username:  MariaTsayo
linkedin_username: maria-tsagiopoulou-106913113
orcid_username: 0000-0002-1653-0327

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Maria_Tsagiopoulou.jpg
about_content: | # this will include new lines to allow paragraphs
  Maria Tsagiopoulou is a postdoctoral researcher at CNAG/CRG on the team of Dr. Ivo Gut. After her BSc in Molecular biology and genetics in 2013, she received her 
  Ph.D. degree from the Biology department of National and Kapodistrian University of Athens in collaboration with the INAB/CERTH in 2019, working under the  
  supervision of Dr. Kostas Stamatopoulos. Her Ph.D. thesis was entitled: «Epigenetic mechanisms in chronic lymphocytic leukemia (CLL)» and was granted by the 
  State Scholarships Foundation of Greece which included 3 publications in the field of epigenetics in CLL. Within the frame of her Ph.D., she established a 
  close collaboration with the team of Dr. Martin-Subero. Their collaboration started in 2017 with a mobility grant from European Hematology Association and is 
  still ongoing with a shared project about histone acetylation profiles of stereotyped subsets in CLL. 
  Her research interests extend to bioinformatics and she participated in bioinformatics courses to strengthen her bioinformatics expertise (Wellcome Sanger Institute,
  EMBO Courses, and EMBL-EBI). In her first position as a Postdoc, graded by the Hellenic Foundation for Research and Innovation with a fellowship of excellence 
  for junior researchers, she was working in the team of Dr. Fotis Psomopoulos. Through this position, she developed new bioinformatics tools using R and machine 
  learning approaches for analyzing or integrating high-throughput data. Moreover, her research interests also include the better use of publicly available high 
  throughput data, in support of open science and reproducibility of scientific results. In this context, she is currently working on the state of the art single-cell 
  technologies studying the immune landscape through different tissues using publicly available data. Finally, she is involved in several data-related training 
  activities such as the activities of the Research Data Alliance which is a global data-sharing community. She has been co-teaching at the CODATA-RDA/ ELIXIR Research
  Data Science Advanced Workshops on Advanced Bioinformatics workshop and she is an Instructor of The Carpentries. Recently, she was awarded as an Early Career on 
  RDA Europe in which she is a co-chair of the Interest Group “Early Career and Engagement” (2021-today).


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: Awards #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
#more_title: Publications #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
 
 
 
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
